config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts  
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, :content, :user_id, presence: true
    default_scope { order('updated_at DESC')}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    respond_to :html


    def index
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def edit
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)        
        flash[:notice] = 'Post was successfully created.' if @post.save
        respond_with @post, :location => root_path       
    end

    def update
        @post = Post.find(params[:id])
        if current_user.id == @post.user_id
            flash[:notice] = 'Post was successfully updated.' if @post.update(post_params)
            respond_with @post, :location => root_path    
        else
            flash[:alert] = 'You don\'t have permission to update this post'
            respond_with @post    
        end         
    end

    def destroy
        @post = Post.find(params[:id])
        if current_user.id == @post.user_id
            flash[:notice] = 'Post was successfully deleted.' if @post.destroy
            respond_with @post, :location => root_path
        else
            flash[:alert] = 'You don\'t have permission to delete this post'
            respond_with @post    
        end 
    end

    
    private

    def post_params
        params.require(:post).permit(:title, :content, :user_id)
    end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boxdevlab</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-end">
        <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to current_user.email, "javascript:void(0);", {:class => "navbar-item"} %>
          <div class="buttons">
            <%= link_to "<strong>Sign out</strong>".html_safe, destroy_user_session_path, {:class => "button is-primary", method: :delete} %>
          </div>
        <% else %>
          <div class="buttons">
            <%= link_to "<strong>Sign up</strong>".html_safe, new_user_registration_path, {:class => "button is-primary"} %>
            <%= link_to "<strong>Sign in</strong>".html_safe, new_user_session_path, {:class => "button is-light"} %>
          </div>
        <% end %>
        </div>
      </div>
  </nav>

    <div class="container">
      <div class="notification is-primary is-hidden">
        <button class="delete"></button>
        <%= notice %>
      </div>
      <div class="notification is-danger is-hidden">
        <button class="delete"></button>
        <%= alert %>
      </div>
      <%= yield %>
    </div>

    <%= javascript_tag do %>
    
      (function name(notice, alert) {
        if (notice !== "") $('div.notification.is-primary').removeClass('is-hidden');      
        if (alert !== "") $('div.notification.is-danger').removeClass('is-hidden');
      })("<%= notice %>", "<%= alert %>")


      document.addEventListener('DOMContentLoaded', () => {
        (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
          var $notification = $delete.parentNode;

          $delete.addEventListener('click', () => {
            $notification.parentNode.removeChild($notification);
          });
        });
      });
    <% end %>

  </body>  
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

<div class="field">
  <label class="label">Post title</label>

  <div class="control">
    <% if @post.errors[:title].first %>
        <%= f.text_field :title, class: "input is-danger" %>
        </div>
        <p class="help is-danger"><%= @post.errors[:title].first %></p>
    <% else %>
        <%= f.text_field :title, class: "input" %>
        </div>
    <% end %>     
</div>

<div class="field">
  <label class="label">Post content</label>

  <div class="control">

   <% if @post.errors[:content].first %>
        <%= f.text_area :content, class: "textarea is-danger" %>
        </div>
        <p class="help is-danger"><%= @post.errors[:content].first %></p>
    <% else %>
            <%= f.text_area :content, class: "textarea" %>
    </div>
    <% end %>  

</div>

<div class="field is-grouped">
  <div class="control">
    <button class="button is-link">Submit</button>
  </div>
  <div class="control">
    <%= link_to "Cancel", root_path, {:class => "button is-link is-light"} %>
  </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= @post.user.email%></strong> <small>at</small> <small><%= @post.updated_at %></small>
          <br>
          <%= @post.title %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <%= link_to "more...", post_path(@post.id), {:class => "level-item"} %>
          <% if user_signed_in? and @post.user_id == current_user.id %>
            <%= link_to edit_post_path(@post.id), {:class => "level-item"} do %>
                <span class="icon is-small">
                <i class="fas fa-edit" aria-hidden="true"></i>
                </span>
            <% end %>
            
            <%= link_to post_path(@post.id), {:class => "level-item", data: {:confirm => "Are you sure ?"}, method: :delete} do %>
                <span class="icon is-small">
                <i class="fas fa-trash" aria-hidden="true"></i>
                </span>
            <% end %>
          <% end %>
      
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <%= link_to "Create post", new_post_path, {:class => "navbar-item"} %>  
<% end %>

<% for  @post in @posts %>
  <%= render "post" %>
<% end  %>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= @post.user.email%></strong> <small>at</small> <small><%= @post.updated_at %></small>
          <br>
          <%= @post.title %>
          <br>
            <%= @post.content %>
        </p>
      </div>
      <nav class="level is-mobile">
        <div class="level-left">
          <%= link_to "Back", root_path, {:class => "level-item"} %>
        </div>
      </nav>
    </div>
  </article>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>